# Generated by Django 3.1.2 on 2021-01-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='my_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.admin'),
        ),
        migrations.AlterField(
            model_name='course',
            name='my_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.admin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='my_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.admin'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='my_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.admin'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=255)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass_class', to='backend_api.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass_teacher', to='backend_api.teacher')),
            ],
        ),
    ]
